import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Menu, ShoppingCart, XIcon } from "lucide-react";
import { Header } from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth scroll-p-80">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#141414]`}
      >
        <div className="mx-auto text-white max-w-[1920px]">
          <Header/>
          {children}

          <footer className="px-4 lg:px-40 xl:px-60 pt-8 text-center">
            {/* footer */}
          </footer>
        </div>
      </body>
    </html>
  );
}
